"""fix typo and add new fields

Revision ID: 0eac8503020b
Revises: 175979ef1d0a
Create Date: 2025-04-27 21:41:49.824719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eac8503020b'
down_revision = '175979ef1d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('race', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loves', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('loves')
        batch_op.drop_column('likes')
        batch_op.drop_column('avatar')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('faculty')
        batch_op.drop_column('race')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
