"""Added verification_status column

Revision ID: 175979ef1d0a
Revises: 
Create Date: 2025-04-27 16:16:31.284214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175979ef1d0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
